### ISSUE TITLE
Server name

### ISSUE THREAD

**Issue by Ultrash0ck** [sadsalat/Orignal-Homigrad#20]
How do i change the server name??

**Comment by uzelezz123** [comment]
homigrad/gamemodes/homigrad/gamemode/game/roundsystem_sv.lua

Find a string with "СЕРВЕР ЛОХОВ" and change it to the name you want to have

**Comment by magmen3** [comment]
> homigrad/gamemodes/homigrad/gamemode/game/roundsystem_sv.lua
> 
> Find a string with "СЕРВЕР ЛОХОВ" and change it to the name you want to have

ххахаххаа а он же раньше вроде секретный сервер назывался
