### ISSUE TITLE
Вопрос?

### ISSUE THREAD

**Issue by Kernantin** [sadsalat/Orignal-Homigrad#30]
Снова здравствуйте разработчики этого режима у меня   есть  вопрос к вам?
Можете ли выложить эту сборку из этого видео https://www.youtube.com/watch?v=Ce3nSKjnpBY или как её получить
Жду ответ на мой вопрос от разработчиков.

**Comment by uzelezz123** [comment]
Чтобы получить эту версию режима нужно для начала изобрести машину времени

**Comment by Kernantin** [comment]
понял ну ты факт говоришь

**Comment by magmen3** [comment]
Ну он прав
